Name: product.rpc
ListenOn: 127.0.0.1:9001
Etcd:
  Hosts:
    - 127.0.0.1:12379
  Key: product.rpc

Mysql:
  DataSource: admin:123456@tcp(127.0.0.1:13306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2fShanghai

CacheRedis:
  - Host: 127.0.0.1:16379
    Type: node

Prometheus:
  Host: 0.0.0.0
  Port: 9091
  Path: /metrics

Telemetry:
  Name: product.rpc
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger