// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/article.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetArticleListRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TagId                uint32   `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	State                uint32   `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{0}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetArticleListRequest) GetTagId() uint32 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *GetArticleListRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Article struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ConverImageUrl       string   `protobuf:"bytes,5,opt,name=conver_image_url,json=converImageUrl,proto3" json:"conver_image_url,omitempty"`
	State                uint32   `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	Tag                  *Tag     `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetConverImageUrl() string {
	if m != nil {
		return m.ConverImageUrl
	}
	return ""
}

func (m *Article) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Article) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GetArticleListReply struct {
	List                 []*Article `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Pager                *Pager     `protobuf:"bytes,2,opt,name=pager,proto3" json:"pager,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetArticleListReply) Reset()         { *m = GetArticleListReply{} }
func (m *GetArticleListReply) String() string { return proto.CompactTextString(m) }
func (*GetArticleListReply) ProtoMessage()    {}
func (*GetArticleListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_60692e730edf4587, []int{2}
}

func (m *GetArticleListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListReply.Unmarshal(m, b)
}
func (m *GetArticleListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListReply.Marshal(b, m, deterministic)
}
func (m *GetArticleListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListReply.Merge(m, src)
}
func (m *GetArticleListReply) XXX_Size() int {
	return xxx_messageInfo_GetArticleListReply.Size(m)
}
func (m *GetArticleListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListReply proto.InternalMessageInfo

func (m *GetArticleListReply) GetList() []*Article {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetArticleListReply) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func init() {
	proto.RegisterType((*GetArticleListRequest)(nil), "proto.GetArticleListRequest")
	proto.RegisterType((*Article)(nil), "proto.Article")
	proto.RegisterType((*GetArticleListReply)(nil), "proto.GetArticleListReply")
}

func init() {
	proto.RegisterFile("proto/article.proto", fileDescriptor_60692e730edf4587)
}

var fileDescriptor_60692e730edf4587 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x86, 0x95, 0xb4, 0x69, 0x35, 0x2e, 0x84, 0x91, 0x87, 0x91, 0xac, 0xaa, 0x8b, 0x2a, 0xab,
	0x6c, 0xd2, 0x88, 0x72, 0x02, 0xd8, 0xa0, 0xd1, 0x20, 0x01, 0x01, 0x36, 0x23, 0xa1, 0xca, 0x75,
	0x9e, 0x8c, 0x25, 0x27, 0x36, 0xf6, 0x6b, 0xa5, 0x6e, 0xb9, 0x02, 0xc7, 0xe1, 0x18, 0x5c, 0x81,
	0x83, 0xa0, 0xd8, 0x19, 0xa6, 0x20, 0x58, 0xd9, 0xef, 0xfb, 0xdf, 0xfb, 0xf3, 0xc7, 0x36, 0xb9,
	0xb2, 0xce, 0xa0, 0xa9, 0xb9, 0x43, 0x25, 0x34, 0x6c, 0x42, 0x45, 0xb3, 0xb0, 0x2c, 0x69, 0xd4,
	0x84, 0xe9, 0x3a, 0xd3, 0x47, 0x69, 0xf9, 0x24, 0x32, 0xe4, 0x72, 0x04, 0x2b, 0x69, 0x8c, 0xd4,
	0x50, 0x73, 0xab, 0x6a, 0xde, 0xf7, 0x06, 0x39, 0x2a, 0xd3, 0xfb, 0xa8, 0x16, 0x77, 0xe4, 0xfa,
	0x15, 0xe0, 0x8b, 0xe8, 0xfe, 0x5a, 0x79, 0x6c, 0xe0, 0xcb, 0x01, 0x3c, 0xd2, 0xa7, 0x24, 0x43,
	0x85, 0x1a, 0x58, 0xb2, 0x4e, 0xca, 0x8b, 0x26, 0x16, 0xf4, 0x9a, 0xcc, 0x90, 0xcb, 0x9d, 0x6a,
	0x59, 0xba, 0x4e, 0xca, 0xc7, 0x4d, 0x86, 0x5c, 0xde, 0xb4, 0x43, 0xb3, 0x47, 0x8e, 0xc0, 0x26,
	0x91, 0x86, 0xa2, 0xf8, 0x9e, 0x90, 0xf9, 0xe8, 0x4c, 0x73, 0x92, 0xaa, 0x36, 0x78, 0x4d, 0x9a,
	0x54, 0xb5, 0x0f, 0xf6, 0xe9, 0xb9, 0x3d, 0x25, 0xd3, 0x16, 0xbc, 0x08, 0x36, 0x17, 0x4d, 0xd8,
	0x53, 0x46, 0xe6, 0xc2, 0xf4, 0x08, 0x3d, 0xb2, 0x69, 0xc0, 0xf7, 0x25, 0x2d, 0xc9, 0xa5, 0x30,
	0xfd, 0x11, 0xdc, 0x4e, 0x75, 0x5c, 0xc2, 0xee, 0xe0, 0x34, 0xcb, 0x42, 0x4b, 0x1e, 0xf9, 0xcd,
	0x80, 0x3f, 0x3a, 0xfd, 0x90, 0x6f, 0x76, 0x96, 0x8f, 0xae, 0xc8, 0x04, 0xb9, 0x64, 0xf3, 0x75,
	0x52, 0x2e, 0xb6, 0x24, 0x1e, 0xc8, 0xe6, 0x03, 0x97, 0xcd, 0x80, 0x8b, 0x4f, 0xe4, 0xea, 0xef,
	0x93, 0xb1, 0xfa, 0x44, 0x0b, 0x32, 0xd5, 0xca, 0x23, 0x4b, 0xd6, 0x93, 0x72, 0xb1, 0xcd, 0xc7,
	0xa9, 0xb1, 0xad, 0x09, 0x1a, 0x2d, 0x48, 0x66, 0xb9, 0x04, 0x17, 0x7e, 0x6e, 0xb1, 0x7d, 0x34,
	0x36, 0xbd, 0x1d, 0x58, 0x13, 0xa5, 0xed, 0x91, 0xe4, 0xe3, 0xd0, 0x7b, 0x70, 0x47, 0x25, 0x80,
	0xb6, 0x24, 0xff, 0xf3, 0x83, 0x74, 0x35, 0x0e, 0xfe, 0xf3, 0x86, 0x96, 0xcb, 0xff, 0xa8, 0x56,
	0x9f, 0x0a, 0xf6, 0xf5, 0xc7, 0xcf, 0x6f, 0x29, 0xa5, 0x97, 0xe1, 0xda, 0x8f, 0xcf, 0xee, 0xdf,
	0x8f, 0x7f, 0xf9, 0xee, 0xee, 0x8d, 0x54, 0xf8, 0xf9, 0xb0, 0xdf, 0x08, 0xd3, 0xd5, 0xfe, 0xd0,
	0x75, 0xe0, 0x6e, 0x6f, 0x6b, 0x69, 0x2a, 0x61, 0x5a, 0xa8, 0x7c, 0xaf, 0xac, 0x05, 0xac, 0xb4,
	0xda, 0x3b, 0xee, 0x4e, 0xb5, 0x74, 0x56, 0x54, 0x7b, 0x6d, 0x64, 0xe5, 0x63, 0xcc, 0xe1, 0x65,
	0xfd, 0xde, 0x87, 0x00, 0xfb, 0x59, 0x58, 0x9e, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x71, 0x7a,
	0x03, 0xdb, 0xab, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleServiceClient interface {
	GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListReply, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListReply, error) {
	out := new(GetArticleListReply)
	err := c.cc.Invoke(ctx, "/proto.ArticleService/GetArticleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
type ArticleServiceServer interface {
	GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListReply, error)
}

// UnimplementedArticleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedArticleServiceServer struct {
}

func (*UnimplementedArticleServiceServer) GetArticleList(ctx context.Context, req *GetArticleListRequest) (*GetArticleListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleList not implemented")
}

func RegisterArticleServiceServer(s *grpc.Server, srv ArticleServiceServer) {
	s.RegisterService(&_ArticleService_serviceDesc, srv)
}

func _ArticleService_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArticleService/GetArticleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleList(ctx, req.(*GetArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleList",
			Handler:    _ArticleService_GetArticleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/article.proto",
}
