Server:
  RunModel: debug
  HttpPort: 8000
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8mb4,utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
